DROP TABLE IF EXISTS DIN_PEV_UT_SITO;
DROP TABLE IF EXISTS ATTIVITA;

CREATE TABLE DIN_PEV_UT_SITO(CODICE_SITO integer NOT NULL, PRIMARY KEY(CODICE_SITO) );
CREATE TABLE ATTIVITA (
  CODICE_ATTIVITA INT NOT NULL PRIMARY KEY,
  CODICE_SITO INTEGER NOT NULL,
  CO_PEV INTEGER NOT NULL,
  NOME_SITO VARCHAR(250),
  REGIONE_OA VARCHAR(50),
  ORIGINE VARCHAR(50),
  STATO_ATTIVITA VARCHAR(20),
  DATA_INS date,
FOREIGN KEY (CODICE_SITO) REFERENCES DIN_PEV_UT_SITO(CODICE_SITO));

INSERT INTO DIN_PEV_UT_SITO (CODICE_SITO) VALUES
('100');
INSERT INTO ATTIVITA (CODICE_ATTIVITA, CODICE_SITO, CO_PEV, NOME_SITO, REGIONE_OA, ORIGINE, STATO_ATTIVITA, DATA_INS) VALUES
(10, 100, 2, 'BFrost_one','Piemonte', 'Nord', 'Attivo', '1961-06-15');